"use client";

import { AnimatePresence, LayoutGroup, motion, useReducedMotion } from "framer-motion";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { MosaicSite, sites as initialSites } from "./data/sites";

const categories = ["Tout", ...Array.from(new Set(initialSites.map((site) => site.category)))];
const recentIds = ["petsitter", "bordeaux-bouge"];

function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    search: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></>, plus: <><path d="M12 5v14M5 12h14" /></>,
    heart: <path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z" />, x: <><path d="m6 6 12 12M18 6 6 18" /></>,
    external: <><path d="M14 4h6v6M20 4 11 13" /><path d="M19 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5" /></>, copy: <><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" /></>, spark: <path d="m12 2 1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7L12 2Z" />,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Cover({ site, large = false }: { site: MosaicSite; large?: boolean }) {
  const kind = site.id;
  return <motion.div layoutId={`cover-${site.id}`} transition={{ type: "spring", damping: 30, stiffness: 260 }} className={`cover cover-${kind} ${large ? "cover-large" : ""}`} style={{ "--accent": site.accent, "--accent-two": site.accentSecondary } as React.CSSProperties}>
    {site.previewImage && <img className="cover-image" src={site.previewImage} alt={`Aperçu de ${site.name}`} />}{kind === "petsitter" && <span className="cover-stamp">BORDEAUX<br />PET CARE</span>}
    {kind === "toit-renov" && <><div className="roof-lines" /><div className="roof-copy">TOIT<br /><i>RÉNOV'</i></div><span className="cover-chip">DEVIS · 24H</span></>}
    {kind === "bordeaux-bouge" && <><div className="city-sun" /><div className="city-bars" /><div className="agenda-paper"><b>SEP</b><strong>18</strong><span>BOUGE</span></div></>}
    {kind === "dashboard" && <><div className="dash-sidebar"><i /><i /><i /></div><div className="dash-main"><span>WEEKLY SIGNALS</span><div className="dash-chart"><i /><i /><i /><i /><i /><i /></div><div className="dash-values"><b>82.4</b><em>+14.2%</em></div></div></>}
    {kind === "keepsurfing" && <><div className="portfolio-type">KEEP<br /><i>SURFING</i></div><div className="portfolio-dot" /><span className="portfolio-foot">Digital craft<br />by Florent Combes</span></>}
    {kind === "rgpd-scan" && <><div className="scanner-window"><header><i /><i /><i /></header><div className="scan-score">94<span>/100</span></div><div className="scan-lines"><i /><i /><i /></div></div><span className="scan-label">CONSENT<br />AUDIT</span></>}
    {kind === "vercel-project" && <><div className="deploy-grid"><span>DEPLOY</span><i /><i /><i /></div><div className="deploy-check">✓</div><small>READY TO SHIP</small></>}
    {kind === "orientation" && <><div className="orbit-lines" /><div className="orbit-card one">DATA</div><div className="orbit-card two">CARE</div><div className="orbit-card three">CREATE</div><div className="orbit-center">YOU</div></>}
    <div className="cover-shade" /><span className="cover-kicker">{site.category}</span>
  </motion.div>;
}

function SiteCard({ site, index, onOpen, favorite, onFavorite, featured = false }: { site: MosaicSite; index: number; onOpen: (site: MosaicSite, el: HTMLElement) => void; favorite: boolean; onFavorite: () => void; featured?: boolean }) {
  const reduce = useReducedMotion();
  const tilt = (event: React.MouseEvent<HTMLElement>) => { if (reduce) return; const bounds = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty("--rx", `${((event.clientY - bounds.top) / bounds.height - .5) * -3}deg`); event.currentTarget.style.setProperty("--ry", `${((event.clientX - bounds.left) / bounds.width - .5) * 3}deg`); event.currentTarget.style.setProperty("--gx", `${((event.clientX - bounds.left) / bounds.width) * 100}%`); event.currentTarget.style.setProperty("--gy", `${((event.clientY - bounds.top) / bounds.height) * 100}%`); };
  return <motion.article layout="position" initial={{ opacity: 0, y: reduce ? 0 : 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .36, delay: Math.min(index * .045, .3), ease: [0.2, .8, .2, 1] }} className={`launch-card ${featured ? "featured-card" : ""}`} onMouseMove={tilt} onMouseLeave={(event) => { event.currentTarget.style.setProperty("--rx", "0deg"); event.currentTarget.style.setProperty("--ry", "0deg"); }}>
    <button className="launch-card-main" onClick={(event) => onOpen(site, event.currentTarget)} aria-label={`Ouvrir ${site.name}`}><Cover site={site} /><div className="card-meta"><div><p>{site.category}</p><h3>{site.name}</h3></div><span className={`state ${site.status === "En ligne" ? "online" : ""}`}>{site.status}</span></div></button>
    <button className={`card-favorite ${favorite ? "is-favorite" : ""}`} onClick={onFavorite} aria-label="Basculer le favori" aria-pressed={favorite}><Icon name="heart" size={16} /></button><span className="card-glint" />
  </motion.article>;
}

export default function Home() {
  const [allSites, setAllSites] = useState<MosaicSite[]>(initialSites); const [query, setQuery] = useState(""); const [category, setCategory] = useState("Tout"); const [selected, setSelected] = useState<MosaicSite | null>(null); const [favorites, setFavorites] = useState<string[]>([]); const [isAdding, setIsAdding] = useState(false); const [copied, setCopied] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null); const triggerRef = useRef<HTMLElement | null>(null); const reduce = useReducedMotion();
  useEffect(() => { const saved = window.localStorage.getItem("mosaic-favorites"); if (saved) setFavorites(JSON.parse(saved)); }, []); useEffect(() => { window.localStorage.setItem("mosaic-favorites", JSON.stringify(favorites)); }, [favorites]);
  const close = () => { setSelected(null); setCopied(false); window.setTimeout(() => triggerRef.current?.focus(), 220); }; useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape") { if (isAdding) setIsAdding(false); else if (selected) close(); } if (event.key === "/" && !selected && !isAdding && document.activeElement?.tagName !== "INPUT") { event.preventDefault(); searchRef.current?.focus(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  const results = useMemo(() => allSites.filter((site) => (category === "Tout" || site.category === category) && [site.name, site.category, ...site.tags].join(" ").toLowerCase().includes(query.toLowerCase())), [allSites, category, query]); const recent = allSites.filter((site) => recentIds.includes(site.id));
  const toggleFavorite = (id: string) => setFavorites((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); const open = (site: MosaicSite, element: HTMLElement) => { triggerRef.current = element; setSelected(site); };
  const addSite = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || "Nouveau site"); setAllSites((current) => [{ id: `${Date.now()}`, name, category: String(form.get("category") || "Personnel"), status: "En ligne", url: String(form.get("url") || "https://example.com"), description: "Un nouvel espace ajouté à votre launchpad.", tags: String(form.get("tags") || "nouveau").split(",").map((tag) => tag.trim()).filter(Boolean), addedAt: "À l’instant", lastAccessed: "Jamais", accent: "#d8ff62", accentSecondary: "#6c70ef", mark: name[0]?.toUpperCase() || "M" }, ...current]); setIsAdding(false); setQuery(""); setCategory("Tout"); };
  const copy = async () => { if (!selected) return; await navigator.clipboard?.writeText(selected.url); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  return <LayoutGroup><main className={`mosaic ${selected ? "drawer-is-open" : ""}`}><div className="ambient-light" /><div className="mosaic-grain" />
    <header className="mosaic-topbar"><a className="mosaic-brand" href="#top"><i>M</i>Mosaic</a><label className="mosaic-search"><Icon name="search" size={17} /><span className="sr-only">Rechercher</span><input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un espace" /><kbd>/</kbd></label><button className="add-button" onClick={() => setIsAdding(true)}><Icon name="plus" size={16} /><span>Ajouter</span></button></header>
    <div className="mosaic-content" id="top"><section className="mosaic-intro"><p><Icon name="spark" size={13} /> YOUR DIGITAL SHELF</p><h1>Vos projets,<em> en mouvement.</em></h1><span>8 espaces actifs · un seul point de départ</span></section>
      <section className="recent-section"><div className="section-heading"><div><p>À LA UNE</p><h2>Reprendre là où vous étiez.</h2></div><span className="section-number">02</span></div><div className="recent-grid">{recent.map((site, index) => <SiteCard key={site.id} site={site} index={index} featured onOpen={open} favorite={favorites.includes(site.id)} onFavorite={() => toggleFavorite(site.id)} />)}</div></section>
      <section className="library-section"><div className="library-bar"><div className="filters" aria-label="Filtrer les projets">{categories.map((item) => <button key={item} className={item === category ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><span>{results.length.toString().padStart(2, "0")} espaces</span></div><div className="launch-grid" onMouseMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty("--light-x", `${event.clientX - rect.left}px`); event.currentTarget.style.setProperty("--light-y", `${event.clientY - rect.top}px`); }}>{results.map((site, index) => <SiteCard key={site.id} site={site} index={index} onOpen={open} favorite={favorites.includes(site.id)} onFavorite={() => toggleFavorite(site.id)} />)}</div>{!results.length && <div className="empty"><Icon name="search" size={25} /><h2>Rien par ici.</h2><button onClick={() => { setQuery(""); setCategory("Tout"); }}>Réinitialiser la recherche</button></div>}</section>
    </div>
    <AnimatePresence>{selected && <><motion.button className="drawer-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close} aria-label="Fermer les détails" /><motion.aside className="site-drawer" role="dialog" aria-modal="true" aria-label={`Détails de ${selected.name}`} initial={reduce ? { opacity: 0 } : { opacity: 0, x: 52 }} animate={{ opacity: 1, x: 0 }} exit={reduce ? { opacity: 0 } : { opacity: 0, x: 52 }} transition={{ type: "spring", damping: 30, stiffness: 280 }}><div className="drawer-top"><span>PROJECT INDEX / {selected.id.toUpperCase()}</span><button onClick={close} aria-label="Fermer"><Icon name="x" /></button></div><Cover site={selected} large /><div className="drawer-body"><div className="drawer-title"><div><p>{selected.category}</p><h2>{selected.name}</h2></div><button className={favorites.includes(selected.id) ? "selected-favorite" : ""} onClick={() => toggleFavorite(selected.id)} aria-label="Favori"><Icon name="heart" /></button></div><p className="drawer-description">{selected.description}</p><div className="drawer-tags">{selected.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div><dl><div><dt>Adresse</dt><dd><a href={selected.url} target="_blank" rel="noreferrer">{selected.url.replace(/^https?:\/\//, "")}</a></dd></div><div><dt>Dernier accès</dt><dd>{selected.lastAccessed}</dd></div><div><dt>Ajouté</dt><dd>{selected.addedAt}</dd></div></dl>{selected.note && <aside className="drawer-note"><b>NOTE</b><p>{selected.note}</p></aside>}<div className="drawer-actions"><a href={selected.url} target="_blank" rel="noreferrer">Ouvrir le site <Icon name="external" size={16} /></a><button onClick={copy}><Icon name="copy" size={16} />{copied ? "Copié" : "Copier le lien"}</button></div></div></motion.aside></>}</AnimatePresence>
    <AnimatePresence>{isAdding && <motion.div className="add-layer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button className="add-shade" onClick={() => setIsAdding(false)} aria-label="Fermer" /><motion.form initial={{ y: 16, scale: .98 }} animate={{ y: 0, scale: 1 }} exit={{ y: 12, scale: .98 }} className="add-form" onSubmit={addSite}><div><p>NOUVEL ESPACE</p><button type="button" onClick={() => setIsAdding(false)} aria-label="Fermer"><Icon name="x" /></button></div><h2>Ajouter au launchpad.</h2><label>Nom<input required name="name" autoFocus placeholder="Ex. Mon nouveau projet" /></label><label>URL<input required name="url" type="url" placeholder="https://" /></label><div className="form-row"><label>Catégorie<select name="category"><option>Applications</option><option>Sites web</option><option>Personnel</option><option>Services</option></select></label><label>Tags<input name="tags" placeholder="design, web" /></label></div><button type="submit">Ajouter l’espace <Icon name="plus" size={16} /></button></motion.form></motion.div>}</AnimatePresence>
  </main></LayoutGroup>;
}
